sudo: required
services: 
  - docker 

before_install:
  - docker build -t ibrahimBelkhiria/docker-react -f Dockerfile.dev .

script:
  - docker run ibrahimBelkhiria/docker-react npm run test -- --coverage
